---
- hosts: localhost
  tasks:
    - name: Deleting resource group - "{{ name }}"
      azure_rm_resourcegroup:
        name: "{{ name }}"
        state: absent
        force_delete_nonempty: yes
      register: rg

    - debug:
        var: rg
